spring:
  application:
    name: provider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: provider
  test:
    name: {cipher}a41bceda800ee5d848a94a7b49a400bab5567e19153f2b1904442ef550598af7
server:
  port: 8094
